### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by hughdavenport** [GovReady/CommonMark-py-Extensions#6]
PR incoming with fixes.

Tests that are failing with links to the GFM spec: [test_break2](https://github.github.com/gfm/#example-202), [test_cols_need_not_match](https://github.github.com/gfm/#example-204), and [test_header_cells_count_matches_delimiter_row](https://github.github.com/gfm/#example-203).

Versions:
```
commonmark           0.8.1
commonmarkextensions 0.0.5
```

Output of `python3 tests.py`.

```
..FF.F.....
======================================================================
FAIL: test_break2 (__main__.GithubFlavoredTablesTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 120, in test_break2
    self.assertRender(
  File "tests.py", line 20, in assertRender
    self.assertEqual(html, expected)
AssertionError: '<tab[121 chars]<td>bar</td>\n<td></td>\n</tr>\n</tbody>\n</table>' != '<tab[121 chars]<td>bar</td>\n<td></td>\n</tr>\n</tbody>\n</table>\n<p>bar</p>'
  <table>
  <thead>
  <tr>
  <th>abc</th>
  <th>def</th>
  </tr>
  </thead>
  <tbody>
  <tr>
  <td>bar</td>
  <td>baz</td>
  </tr>
  <tr>
  <td>bar</td>
  <td></td>
  </tr>
  </tbody>
- </table>+ </table>
?         +
+ <p>bar</p>

======================================================================
FAIL: test_cols_need_not_match (__main__.GithubFlavoredTablesTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 159, in test_cols_need_not_match
    self.assertRender(
  File "tests.py", line 20, in assertRender
    self.assertEqual(html, expected)
AssertionError: '<tab[123 chars]ar</td>\n<td>baz</td>\n<td>boo</td>\n</tr>\n</tbody>\n</table>' != '<tab[123 chars]ar</td>\n<td>baz</td>\n</tr>\n</tbody>\n</table>'
  <table>
  <thead>
  <tr>
  <th>abc</th>
  <th>def</th>
  </tr>
  </thead>
  <tbody>
  <tr>
  <td>bar</td>
  <td></td>
  </tr>
  <tr>
  <td>bar</td>
  <td>baz</td>
- <td>boo</td>
  </tr>
  </tbody>
  </table>

======================================================================
FAIL: test_header_cells_count_matches_delimiter_row (__main__.GithubFlavoredTablesTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests.py", line 148, in test_header_cells_count_matches_delimiter_row
    self.assertRender(
  File "tests.py", line 20, in assertRender
    self.assertEqual(html, expected)
AssertionError: '<table>\n<thead>\n<tr>\n<th>abc</th>\n<th>[88 chars]ble>' != '<p>| abc | def |\n| --- |\n| bar |</p>'
+ <p>| abc | def |
+ | --- |
+ | bar |</p>- <table>
- <thead>
- <tr>
- <th>abc</th>
- <th>def</th>
- </tr>
- </thead>
- <tbody>
- <tr>
- <td>bar</td>
- <td></td>
- </tr>
- </tbody>
- </table>

----------------------------------------------------------------------
Ran 11 tests in 0.050s

FAILED (failures=3)
```

**Comment by hughdavenport** [comment]
My latest PR (#11) may have broken this. Have not tested
